language: node_js
node_js: '8.10'

script: npm run test

before_deploy:
  - npm run build

deploy:
  # India Dev Webhook
  - provider: lambda
    function_name: "cognicity-line-webhook-dev"
    region: $AWS_REGION_IN
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/receive"
    handler_name: "default"
    on:
      branch: dev
  # India Dev Reply
  - provider: lambda
    function_name: "cognicity-line-reply-dev"
    region: $AWS_REGION_IN
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/send"
    handler_name: "default"
    on:
      branch: dev

  # India Prod Webhook
  - provider: lambda
    function_name: "cognicity-line-webhook-prod"
    region: $AWS_REGION_IN
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/receive"
    handler_name: "default"
    on:
      branch: master
  # India Prod Reply
  - provider: lambda
    function_name: "cognicity-line-reply-prod"
    region: $AWS_REGION_IN
    role: $AWS_LAMBDA_ROLE
    runtime: "nodejs8.10"
    module_name: "bin/functions/send"
    handler_name: "default"
    on:
      branch: master
